name: contract_validator
description: Standalone CLI to validate canonical JSON contracts
version: 0.1.0
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  # Keep dependencies minimal; using only core libraries in code
  # Add 'args' if you want robust CLI parsing later
  # args: ^2.5.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0